name: Spell Check

on:
  pull_request:
  push:
    branches:
      - main
  merge_group:

jobs:
  typos:
    name: Typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check spelling
        uses: crate-ci/typos@v1.32.0
